---
apiVersion: identity.aws.crossplane.io/v1alpha3
kind: IAMRole
metadata:
  name: crossplane-eks-cluster-role
spec:
  roleName: crossplane-eks-cluster-role
  description: a role that gives eks power
  assumeRolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Service": "eks.amazonaws.com"
          },
          "Action": "sts:AssumeRole"
        }
      ]
    }
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
---
apiVersion: identity.aws.crossplane.io/v1alpha3
kind: IAMRolePolicyAttachment
metadata:
  name: crossplane-role-servicepolicy
spec:
  roleNameRef:
    name: crossplane-eks-cluster-role
  # wellknown policy arn
  policyArn: arn:aws:iam::aws:policy/AmazonEKSServicePolicy
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
---
apiVersion: identity.aws.crossplane.io/v1alpha3
kind: IAMRolePolicyAttachment
metadata:
  name: crossplane-role-clusterpolicy
spec:
  roleNameRef:
    name: crossplane-eks-cluster-role
  # wellknown policy arn
  policyArn: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  reclaimPolicy: Delete
  providerRef:
    name: aws-provider
