apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-deploy
spec:
  # profile: demo
  profile: default
  # components:
  #   cni:
  #     enabled: true
  # values:
  #   cni:
  #     excludeNamespaces:
  #      - istio-system
  #      - kube-system
  #      - styra-system
  #     logLevel: info